### ISSUE TITLE
Not able to migrate to or use setup-tools

### ISSUE THREAD

**Issue by Exnadella** [buildpacks/github-actions#189]
Hi,

We have tried to use the setup-tools and getting the following issue.
![Screenshot 2023-03-13 144544](https://user-images.githubusercontent.com/22579094/224738780-85183b3f-63e8-4d61-890a-8f28b3946196.jpg)
![Screenshot 2023-03-13 144611](https://user-images.githubusercontent.com/22579094/224738761-a1bba70b-f0b4-4095-af79-b6d7d31dd69a.jpg)

**Comment by edmorley** [comment]
Hi! This was fixed in `setup-tools@5.0.1`, which was released back in January. Could you switch to a newer release?

**Comment by Exnadella** [comment]
Hi,

I also tried with the setup-tools@5.0.1 and found the same issue, if we use setup-tools does it not use the pack?

Thanks,
Ranganath.

**Comment by edmorley** [comment]
@Exnadella `setup-tools` does not install Pack CLI, it only installs some other useful tools (hence the name). If you need Pack CLI, you need to continue to use `setup-pack`.

See the descriptions here:
https://github.com/buildpacks/github-actions#setup-pack-cli-action
https://github.com/buildpacks/github-actions#setup-tools-action

**Comment by Exnadella** [comment]
Thanks for the update, we can close this issue.
