### ISSUE TITLE
Verify Namespace Owner Action should accept a blocklist

### ISSUE THREAD

**Issue by jkutner** [buildpacks/github-actions#35]
The [Verify Namespace Owner Action](https://github.com/buildpacks/github-actions#verify-namespace-owner-action) should accept a `blocklist` array of namespaces names to disallow. This would be used when `add-if-missing` is set to `true`.

This would likely be implemented as a new field on the [`config` struct in `verify_namespace_owner.go`](https://github.com/buildpacks/github-actions/blob/main/registry/verify-namespace-owner/verify_namespace_owner.go#L68), and then validated in the same way as [`AddIfMissing` in that file](https://github.com/buildpacks/github-actions/blob/main/registry/verify-namespace-owner/verify_namespace_owner.go#L117)

I'm not sure how Github passes arrays as params, so it might be best for this action to accept a comma delimited string (commas are not allowed in namespaces, so it's an acceptable delimiter)

**Comment by jkutner** [comment]
The "namespace" is a component of the [Buildpack ID](https://github.com/buildpacks/spec/blob/main/extensions/buildpack-registry.md#buildpack-id) as described in the Buildpack Registry spec.

**Comment by mritunjaysharma394** [comment]
Hi @jkutner, thank you so much for the clarification! I will start working on this issue!

**Comment by srisatya1197** [comment]
Is anyone working on this issue? If not I want to.

**Comment by mritunjaysharma394** [comment]
Hi @srisatya1197, I have already started working on this issue and will be hopefully creating the PR tomorrow, thanks :))
